MODULE GETDATA_MOD

INTERFACE REPLICATE
  MODULE PROCEDURE REPLICATE3
  MODULE PROCEDURE REPLICATE4
END INTERFACE

INTERFACE NPROMIZE
  MODULE PROCEDURE NPROMIZE4
  MODULE PROCEDURE NPROMIZE5
END INTERFACE

CONTAINS

SUBROUTINE GETDATA (NPROMA, NGPBLKS, PZZF, PRHODJ, PEXNREF, PRHODREF, PPABSM,   &
& PTHT, PSIGS, PMFCONV, PRC_MF, PRI_MF, PCF_MF, PTHS, PRS, PSRCS, PCLDFR,       &
& PHLC_HRC, PHLC_HCF, PHLI_HRI, PHLI_HCF, ZRS, ZZZ, PRS_OUT, PSRCS_OUT,         &
& PCLDFR_OUT, PHLC_HRC_OUT, PHLC_HCF_OUT, PHLI_HRI_OUT, PHLI_HCF_OUT)

IMPLICIT NONE

INTEGER, PARAMETER :: IFILE = 77

INTEGER      :: KLON 
INTEGER      :: KIDIA  
INTEGER      :: KFDIA  
INTEGER      :: KLEV  
INTEGER      :: KRR  
INTEGER      :: KDUM

REAL, ALLOCATABLE   :: PZZF           (:,:,:,:)   
REAL, ALLOCATABLE   :: PRHODJ         (:,:,:,:)   
REAL, ALLOCATABLE   :: PEXNREF        (:,:,:,:)   
REAL, ALLOCATABLE   :: PRHODREF       (:,:,:,:)   
REAL, ALLOCATABLE   :: PPABSM         (:,:,:,:)   
REAL, ALLOCATABLE   :: PTHT           (:,:,:,:)   
REAL, ALLOCATABLE   :: PSIGS          (:,:,:,:)   
REAL, ALLOCATABLE   :: PMFCONV        (:,:,:,:)   
REAL, ALLOCATABLE   :: PRC_MF         (:,:,:,:)   
REAL, ALLOCATABLE   :: PRI_MF         (:,:,:,:)   
REAL, ALLOCATABLE   :: PCF_MF         (:,:,:,:)   
REAL, ALLOCATABLE   :: PTHS           (:,:,:,:)   
REAL, ALLOCATABLE   :: PRS            (:,:,:,:,:) 
REAL, ALLOCATABLE   :: PRS_OUT        (:,:,:,:,:) 
REAL, ALLOCATABLE   :: PSRCS          (:,:,:,:)   
REAL, ALLOCATABLE   :: PSRCS_OUT      (:,:,:,:)   
REAL, ALLOCATABLE   :: PCLDFR         (:,:,:,:)   
REAL, ALLOCATABLE   :: PCLDFR_OUT     (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HRC       (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HRC_OUT   (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HCF       (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HCF_OUT   (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HRI       (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HRI_OUT   (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HCF       (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HCF_OUT   (:,:,:,:)   
REAL, ALLOCATABLE   :: ZRS            (:,:,:,:,:) 
REAL, ALLOCATABLE   :: ZZZ            (:,:,:,:)   

INTEGER :: NGPTOT, NPROMA, NGPBLKS
INTEGER :: IOFF, IBL
LOGICAL :: LLEXIST
CHARACTER(LEN=32) :: CLFILE

KRR=6
NGPTOT = NPROMA * NGPBLKS

IOFF = 0
IBL = 1

DO IBL = 1, 296
  WRITE (CLFILE, '("data/",I3.3,".dat")') IBL

  INQUIRE (FILE=TRIM (CLFILE), EXIST=LLEXIST)

  PRINT *, CLFILE

  IF (.NOT. LLEXIST) EXIT

  OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED') 
  
  READ (IFILE) KLON, KDUM, KLEV

  IF (IBL == 1) THEN
    ALLOCATE (PZZF         (NGPTOT,1,KLEV,1))
    ALLOCATE (PRHODJ       (NGPTOT,1,KLEV,1))
    ALLOCATE (PEXNREF      (NGPTOT,1,KLEV,1))
    ALLOCATE (PRHODREF     (NGPTOT,1,KLEV,1))
    ALLOCATE (PPABSM       (NGPTOT,1,KLEV,1))
    ALLOCATE (PTHT         (NGPTOT,1,KLEV,1))
    ALLOCATE (PSIGS        (NGPTOT,1,KLEV,1))
    ALLOCATE (PMFCONV      (NGPTOT,1,KLEV,1))
    ALLOCATE (PRC_MF       (NGPTOT,1,KLEV,1))
    ALLOCATE (PRI_MF       (NGPTOT,1,KLEV,1))
    ALLOCATE (PCF_MF       (NGPTOT,1,KLEV,1))
    ALLOCATE (PTHS         (NGPTOT,1,KLEV,1))
    ALLOCATE (PRS          (NGPTOT,1,KLEV,KRR,1))
    ALLOCATE (PRS_OUT      (NGPTOT,1,KLEV,KRR,1))
    ALLOCATE (PSRCS        (NGPTOT,1,KLEV,1))
    ALLOCATE (PSRCS_OUT    (NGPTOT,1,KLEV,1))
    ALLOCATE (PCLDFR       (NGPTOT,1,KLEV,1))
    ALLOCATE (PCLDFR_OUT   (NGPTOT,1,KLEV,1))
    ALLOCATE (ZRS          (NGPTOT,1,KLEV,0:KRR,1))
    ALLOCATE (ZZZ          (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLC_HRC     (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLC_HRC_OUT (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLC_HCF     (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLC_HCF_OUT (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLI_HRI     (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLI_HRI_OUT (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLI_HCF     (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLI_HCF_OUT (NGPTOT,1,KLEV,1))
  ENDIF

  IF (IOFF+KLON > NGPTOT) EXIT

  READ (IFILE) PRHODJ       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PEXNREF      (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PRHODREF     (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PSIGS        (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PMFCONV      (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PPABSM       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) ZZZ          (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PCF_MF       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PRC_MF       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PRI_MF       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) ZRS          (IOFF+1:IOFF+KLON,:,:,:,1) 
  READ (IFILE) PRS          (IOFF+1:IOFF+KLON,:,:,:,1) 
  READ (IFILE) PTHS         (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PRS_OUT      (IOFF+1:IOFF+KLON,:,:,:,1) 
  READ (IFILE) PSRCS_OUT    (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PCLDFR_OUT   (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PHLC_HRC_OUT (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PHLC_HCF_OUT (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PHLI_HRI_OUT (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PHLI_HCF_OUT (IOFF+1:IOFF+KLON,:,:,1) 
  
  CLOSE (IFILE)

  IOFF = IOFF + KLON

ENDDO

CALL REPLICATE (IOFF, PRHODJ       (:,:,:,1))
CALL REPLICATE (IOFF, PEXNREF      (:,:,:,1))
CALL REPLICATE (IOFF, PRHODREF     (:,:,:,1))
CALL REPLICATE (IOFF, PSIGS        (:,:,:,1))
CALL REPLICATE (IOFF, PMFCONV      (:,:,:,1))
CALL REPLICATE (IOFF, PPABSM       (:,:,:,1))
CALL REPLICATE (IOFF, ZZZ          (:,:,:,1))
CALL REPLICATE (IOFF, PCF_MF       (:,:,:,1))
CALL REPLICATE (IOFF, PRC_MF       (:,:,:,1))
CALL REPLICATE (IOFF, PRI_MF       (:,:,:,1))
CALL REPLICATE (IOFF, ZRS          (:,:,:,:,1))
CALL REPLICATE (IOFF, PRS          (:,:,:,:,1))
CALL REPLICATE (IOFF, PTHS         (:,:,:,1))
CALL REPLICATE (IOFF, PRS_OUT      (:,:,:,:,1))
CALL REPLICATE (IOFF, PSRCS_OUT    (:,:,:,1))
CALL REPLICATE (IOFF, PCLDFR_OUT   (:,:,:,1))
CALL REPLICATE (IOFF, PHLC_HRC_OUT (:,:,:,1))
CALL REPLICATE (IOFF, PHLC_HCF_OUT (:,:,:,1))
CALL REPLICATE (IOFF, PHLI_HRI_OUT (:,:,:,1))
CALL REPLICATE (IOFF, PHLI_HCF_OUT (:,:,:,1))

CALL NPROMIZE (NPROMA, PRHODJ      )
CALL NPROMIZE (NPROMA, PEXNREF     )
CALL NPROMIZE (NPROMA, PRHODREF    )
CALL NPROMIZE (NPROMA, PSIGS       )
CALL NPROMIZE (NPROMA, PMFCONV     )
CALL NPROMIZE (NPROMA, PPABSM      )
CALL NPROMIZE (NPROMA, ZZZ         )
CALL NPROMIZE (NPROMA, PCF_MF      )
CALL NPROMIZE (NPROMA, PRC_MF      )
CALL NPROMIZE (NPROMA, PRI_MF      )
CALL NPROMIZE (NPROMA, ZRS         )
CALL NPROMIZE (NPROMA, PRS         )
CALL NPROMIZE (NPROMA, PTHS        )
CALL NPROMIZE (NPROMA, PRS_OUT     )
CALL NPROMIZE (NPROMA, PSRCS_OUT   )
CALL NPROMIZE (NPROMA, PCLDFR_OUT  )
CALL NPROMIZE (NPROMA, PHLC_HRC_OUT)
CALL NPROMIZE (NPROMA, PHLC_HCF_OUT)
CALL NPROMIZE (NPROMA, PHLI_HRI_OUT)
CALL NPROMIZE (NPROMA, PHLI_HCF_OUT)

END SUBROUTINE 

SUBROUTINE REPLICATE4 (KOFF, P)

INTEGER :: KOFF
REAL    :: P (:,:,:,:)

INTEGER :: I, J

DO I = KOFF, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF-1)
  P (I, :, :, :) = P (J, :, :, :)
ENDDO

END SUBROUTINE

SUBROUTINE REPLICATE3 (KOFF, P)

INTEGER :: KOFF
REAL    :: P (:,:,:)

INTEGER :: I, J

DO I = KOFF, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF-1)
  P (I, :, :) = P (J, :, :)
ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE4 (KPROMA, P)

INTEGER :: KPROMA
REAL, ALLOCATABLE :: P (:,:,:,:)

REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3), &
         & LBOUND (P, 4):UBOUND (P, 4))

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (P, 4) /= 1) STOP 1

IGPTOT = SIZE (P, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

Z = P

DEALLOCATE (P)

ALLOCATE (P (KPROMA, LBOUND (Z, 2):UBOUND (Z, 2), &
          &          LBOUND (Z, 3):UBOUND (Z, 3), &
          & IGPBLK))

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    P (JLON, :, :, IBL) = Z (IGP + (JLON - 1), :, :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    P (JLON, :, :, IBL) = P (JFDIA, :, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE5 (KPROMA, P)

INTEGER :: KPROMA
REAL, ALLOCATABLE :: P (:,:,:,:,:)

REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3), &
         & LBOUND (P, 4):UBOUND (P, 4), &
         & LBOUND (P, 5):UBOUND (P, 5))

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (P, 5) /= 1) STOP 1

IGPTOT = SIZE (P, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

Z = P

DEALLOCATE (P)

ALLOCATE (P (KPROMA, LBOUND (Z, 2):UBOUND (Z, 2), &
          &          LBOUND (Z, 3):UBOUND (Z, 3), &
          &          LBOUND (Z, 4):UBOUND (Z, 4), &
          & IGPBLK))

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    P (JLON, :, :, :, IBL) = Z (IGP + (JLON - 1), :, :, :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    P (JLON, :, :, :, IBL) = P (JFDIA, :, :, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

END  MODULE
