MODULE GETDATA_MOD

INTERFACE REPLICATE
  MODULE PROCEDURE REPLICATE3
  MODULE PROCEDURE REPLICATE4
END INTERFACE

INTERFACE NPROMIZE
  MODULE PROCEDURE NPROMIZE4
  MODULE PROCEDURE NPROMIZE5
END INTERFACE

INTERFACE INTERPOLATE
  MODULE PROCEDURE INTERPOLATE4
  MODULE PROCEDURE INTERPOLATE5
END INTERFACE

CONTAINS

SUBROUTINE GETDATA (NPROMA, NGPBLKS, NFLEVG, PRHODJ, PEXNREF, PRHODREF, PPABSM, PTHT, ZICE_CLD_WGT, &
& ZSIGQSAT, PSIGS, PMFCONV, PRC_MF, PRI_MF, PCF_MF, PTHS, PRS, PSRCS, PCLDFR, PHLC_HRC, PHLC_HCF,   &
& PHLI_HRI, PHLI_HCF, ZRS, ZZZ, PRS_OUT, PSRCS_OUT, PCLDFR_OUT, PHLC_HRC_OUT, PHLC_HCF_OUT,         &
& PHLI_HRI_OUT, PHLI_HCF_OUT)

IMPLICIT NONE

INTEGER, PARAMETER :: IFILE = 77

INTEGER      :: KLON 
INTEGER      :: KIDIA  
INTEGER      :: KFDIA  
INTEGER      :: KLEV  
INTEGER      :: KRR  
INTEGER      :: KDUM

REAL, ALLOCATABLE   :: PRHODJ         (:,:,:,:)   
REAL, ALLOCATABLE   :: PEXNREF        (:,:,:,:)   
REAL, ALLOCATABLE   :: PRHODREF       (:,:,:,:)   
REAL, ALLOCATABLE   :: PPABSM         (:,:,:,:)   
REAL, ALLOCATABLE   :: PTHT           (:,:,:,:)   
REAL, ALLOCATABLE   :: ZICE_CLD_WGT   (:,:,:)
REAL, ALLOCATABLE   :: ZSIGQSAT       (:,:,:)
REAL, ALLOCATABLE   :: PSIGS          (:,:,:,:)   
REAL, ALLOCATABLE   :: PMFCONV        (:,:,:,:)   
REAL, ALLOCATABLE   :: PRC_MF         (:,:,:,:)   
REAL, ALLOCATABLE   :: PRI_MF         (:,:,:,:)   
REAL, ALLOCATABLE   :: PCF_MF         (:,:,:,:)   
REAL, ALLOCATABLE   :: PTHS           (:,:,:,:)   
REAL, ALLOCATABLE   :: PRS            (:,:,:,:,:) 
REAL, ALLOCATABLE   :: PRS_OUT        (:,:,:,:,:) 
REAL, ALLOCATABLE   :: PSRCS          (:,:,:,:)   
REAL, ALLOCATABLE   :: PSRCS_OUT      (:,:,:,:)   
REAL, ALLOCATABLE   :: PCLDFR         (:,:,:,:)   
REAL, ALLOCATABLE   :: PCLDFR_OUT     (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HRC       (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HRC_OUT   (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HCF       (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HCF_OUT   (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HRI       (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HRI_OUT   (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HCF       (:,:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HCF_OUT   (:,:,:,:)   
REAL, ALLOCATABLE   :: ZRS            (:,:,:,:,:) 
REAL, ALLOCATABLE   :: ZZZ            (:,:,:,:)   

INTEGER :: NGPTOT, NPROMA, NGPBLKS, NFLEVG
INTEGER :: IOFF, IBL
LOGICAL :: LLEXIST
CHARACTER(LEN=32) :: CLFILE

KRR=6
NGPTOT = NPROMA * NGPBLKS

IOFF = 0
IBL = 1

DO IBL = 1, 296
  WRITE (CLFILE, '("data/",I3.3,".dat")') IBL

  INQUIRE (FILE=TRIM (CLFILE), EXIST=LLEXIST)

  PRINT *, CLFILE

  IF (.NOT. LLEXIST) EXIT

  OPEN (IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED') 
  
  READ (IFILE) KLON, KDUM, KLEV

  IF (IBL == 1) THEN
    ALLOCATE (PRHODJ       (NGPTOT,1,KLEV,1))
    ALLOCATE (PEXNREF      (NGPTOT,1,KLEV,1))
    ALLOCATE (PRHODREF     (NGPTOT,1,KLEV,1))
    ALLOCATE (PPABSM       (NGPTOT,1,KLEV,1))
    ALLOCATE (PTHT         (NGPTOT,1,KLEV,1))
    ALLOCATE (PSIGS        (NGPTOT,1,KLEV,1))
    ALLOCATE (PMFCONV      (NGPTOT,1,KLEV,1))
    ALLOCATE (PRC_MF       (NGPTOT,1,KLEV,1))
    ALLOCATE (PRI_MF       (NGPTOT,1,KLEV,1))
    ALLOCATE (PCF_MF       (NGPTOT,1,KLEV,1))
    ALLOCATE (PTHS         (NGPTOT,1,KLEV,1))
    ALLOCATE (PRS          (NGPTOT,1,KLEV,KRR,1))
    ALLOCATE (PRS_OUT      (NGPTOT,1,KLEV,KRR,1))
    ALLOCATE (PSRCS        (NGPTOT,1,KLEV,1))
    ALLOCATE (PSRCS_OUT    (NGPTOT,1,KLEV,1))
    ALLOCATE (PCLDFR       (NGPTOT,1,KLEV,1))
    ALLOCATE (PCLDFR_OUT   (NGPTOT,1,KLEV,1))
    ALLOCATE (ZRS          (NGPTOT,1,KLEV,0:KRR,1))
    ALLOCATE (ZZZ          (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLC_HRC     (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLC_HRC_OUT (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLC_HCF     (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLC_HCF_OUT (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLI_HRI     (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLI_HRI_OUT (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLI_HCF     (NGPTOT,1,KLEV,1))
    ALLOCATE (PHLI_HCF_OUT (NGPTOT,1,KLEV,1))
  ENDIF

  IF (IOFF+KLON > NGPTOT) EXIT

  READ (IFILE) PRHODJ       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PEXNREF      (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PRHODREF     (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PSIGS        (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PMFCONV      (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PPABSM       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) ZZZ          (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PCF_MF       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PRC_MF       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PRI_MF       (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) ZRS          (IOFF+1:IOFF+KLON,:,:,:,1) 
  READ (IFILE) PRS          (IOFF+1:IOFF+KLON,:,:,:,1) 
  READ (IFILE) PTHS         (IOFF+1:IOFF+KLON,:,:,1)
  READ (IFILE) PRS_OUT      (IOFF+1:IOFF+KLON,:,:,:,1) 
  READ (IFILE) PSRCS_OUT    (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PCLDFR_OUT   (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PHLC_HRC_OUT (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PHLC_HCF_OUT (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PHLI_HRI_OUT (IOFF+1:IOFF+KLON,:,:,1) 
  READ (IFILE) PHLI_HCF_OUT (IOFF+1:IOFF+KLON,:,:,1) 
  
  CLOSE (IFILE)

  IOFF = IOFF + KLON

ENDDO

IF (NFLEVG > 0) THEN
  CALL INTERPOLATE (NFLEVG, IOFF, PRHODJ      )
  CALL INTERPOLATE (NFLEVG, IOFF, PEXNREF     )
  CALL INTERPOLATE (NFLEVG, IOFF, PRHODREF    )
  CALL INTERPOLATE (NFLEVG, IOFF, PSIGS       )
  CALL INTERPOLATE (NFLEVG, IOFF, PMFCONV     )
  CALL INTERPOLATE (NFLEVG, IOFF, PPABSM      )
  CALL INTERPOLATE (NFLEVG, IOFF, ZZZ         )
  CALL INTERPOLATE (NFLEVG, IOFF, PCF_MF      )
  CALL INTERPOLATE (NFLEVG, IOFF, PRC_MF      )
  CALL INTERPOLATE (NFLEVG, IOFF, PRI_MF      )
  CALL INTERPOLATE (NFLEVG, IOFF, ZRS         )
  CALL INTERPOLATE (NFLEVG, IOFF, PRS         )
  CALL INTERPOLATE (NFLEVG, IOFF, PTHS        )
  CALL INTERPOLATE (NFLEVG, IOFF, PRS_OUT     )
  CALL INTERPOLATE (NFLEVG, IOFF, PSRCS_OUT   )
  CALL INTERPOLATE (NFLEVG, IOFF, PCLDFR_OUT  )
  CALL INTERPOLATE (NFLEVG, IOFF, PHLC_HRC_OUT)
  CALL INTERPOLATE (NFLEVG, IOFF, PHLC_HCF_OUT)
  CALL INTERPOLATE (NFLEVG, IOFF, PHLI_HRI_OUT)
  CALL INTERPOLATE (NFLEVG, IOFF, PHLI_HCF_OUT)
ENDIF

CALL REPLICATE (IOFF, PRHODJ       (:, :, :, 1))
CALL REPLICATE (IOFF, PEXNREF      (:, :, :, 1))
CALL REPLICATE (IOFF, PRHODREF     (:, :, :, 1))
CALL REPLICATE (IOFF, PSIGS        (:, :, :, 1))
CALL REPLICATE (IOFF, PMFCONV      (:, :, :, 1))
CALL REPLICATE (IOFF, PPABSM       (:, :, :, 1))
CALL REPLICATE (IOFF, ZZZ          (:, :, :, 1))
CALL REPLICATE (IOFF, PCF_MF       (:, :, :, 1))
CALL REPLICATE (IOFF, PRC_MF       (:, :, :, 1))
CALL REPLICATE (IOFF, PRI_MF       (:, :, :, 1))
CALL REPLICATE (IOFF, ZRS          (:, :, :, :, 1))
CALL REPLICATE (IOFF, PRS          (:, :, :, :, 1))
CALL REPLICATE (IOFF, PTHS         (:, :, :, 1))
CALL REPLICATE (IOFF, PRS_OUT      (:, :, :, :, 1))
CALL REPLICATE (IOFF, PSRCS_OUT    (:, :, :, 1))
CALL REPLICATE (IOFF, PCLDFR_OUT   (:, :, :, 1))
CALL REPLICATE (IOFF, PHLC_HRC_OUT (:, :, :, 1))
CALL REPLICATE (IOFF, PHLC_HCF_OUT (:, :, :, 1))
CALL REPLICATE (IOFF, PHLI_HRI_OUT (:, :, :, 1))
CALL REPLICATE (IOFF, PHLI_HCF_OUT (:, :, :, 1))

CALL NPROMIZE (NPROMA, PRHODJ      )
CALL NPROMIZE (NPROMA, PEXNREF     )
CALL NPROMIZE (NPROMA, PRHODREF    )
CALL NPROMIZE (NPROMA, PSIGS       )
CALL NPROMIZE (NPROMA, PMFCONV     )
CALL NPROMIZE (NPROMA, PPABSM      )
CALL NPROMIZE (NPROMA, ZZZ         )
CALL NPROMIZE (NPROMA, PCF_MF      )
CALL NPROMIZE (NPROMA, PRC_MF      )
CALL NPROMIZE (NPROMA, PRI_MF      )
CALL NPROMIZE (NPROMA, ZRS         )
CALL NPROMIZE (NPROMA, PRS         )
CALL NPROMIZE (NPROMA, PTHS        )
CALL NPROMIZE (NPROMA, PRS_OUT     )
CALL NPROMIZE (NPROMA, PSRCS_OUT   )
CALL NPROMIZE (NPROMA, PCLDFR_OUT  )
CALL NPROMIZE (NPROMA, PHLC_HRC_OUT)
CALL NPROMIZE (NPROMA, PHLC_HCF_OUT)
CALL NPROMIZE (NPROMA, PHLI_HRI_OUT)
CALL NPROMIZE (NPROMA, PHLI_HCF_OUT)

ALLOCATE (ZSIGQSAT (NPROMA, 1, NGPBLKS))
ZSIGQSAT = 2.0000000000000000E-002

ALLOCATE (ZICE_CLD_WGT (NPROMA, 1, NGPBLKS))
ZICE_CLD_WGT = 1.5

END SUBROUTINE 

SUBROUTINE REPLICATE4 (KOFF, P)

INTEGER :: KOFF
REAL    :: P (:,:,:,:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I, :, :, :) = P (J, :, :, :)
ENDDO

END SUBROUTINE

SUBROUTINE REPLICATE3 (KOFF, P)

INTEGER :: KOFF
REAL    :: P (:,:,:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I, :, :) = P (J, :, :)
ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE4 (KPROMA, P)

INTEGER :: KPROMA
REAL, ALLOCATABLE :: P (:,:,:,:)

REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3), &
         & LBOUND (P, 4):UBOUND (P, 4))

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (P, 4) /= 1) STOP 1

IGPTOT = SIZE (P, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

Z = P

DEALLOCATE (P)

ALLOCATE (P (KPROMA, LBOUND (Z, 2):UBOUND (Z, 2), &
          &          LBOUND (Z, 3):UBOUND (Z, 3), &
          & IGPBLK))

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    P (JLON, :, :, IBL) = Z (IGP + (JLON - 1), :, :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    P (JLON, :, :, IBL) = P (JFDIA, :, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE5 (KPROMA, P)

INTEGER :: KPROMA
REAL, ALLOCATABLE :: P (:,:,:,:,:)

REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3), &
         & LBOUND (P, 4):UBOUND (P, 4), &
         & LBOUND (P, 5):UBOUND (P, 5))

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (P, 5) /= 1) STOP 1

IGPTOT = SIZE (P, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

Z = P

DEALLOCATE (P)

ALLOCATE (P (KPROMA, LBOUND (Z, 2):UBOUND (Z, 2), &
          &          LBOUND (Z, 3):UBOUND (Z, 3), &
          &          LBOUND (Z, 4):UBOUND (Z, 4), &
          & IGPBLK))

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    P (JLON, :, :, :, IBL) = Z (IGP + (JLON - 1), :, :, :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    P (JLON, :, :, :, IBL) = P (JFDIA, :, :, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE INTERPOLATE4 (KFLEVG, KOFF, P)

INTEGER :: KFLEVG, KOFF
REAL, ALLOCATABLE :: P (:,:,:,:)
REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3), &
         & LBOUND (P, 4):UBOUND (P, 4))
INTEGER :: ILEV1A, ILEV1B, ILEV2, NLEV1, NLEV2
REAL :: ZWA, ZWB, ZLEV1, ZLEV2

Z = P

NLEV1 = SIZE (P, 3)
NLEV2 = KFLEVG

DEALLOCATE (P)

ALLOCATE (P (LBOUND (Z, 1):UBOUND (Z, 1), &
           & LBOUND (Z, 2):UBOUND (Z, 2), &
           & KFLEVG, &
           & LBOUND (Z, 4):UBOUND (Z, 4)))

DO ILEV2 = 1, ILEV2
  ZLEV2 = REAL (ILEV2 - 1) / REAL (NLEV2 -1)
  ZLEV1 = 1. + ZWA * REAL (NLEV1 - 1)
  ILEV1B = MIN (CEILING (ZLEV1), NLEV1)
  ILEV1A = MAX (FLOOR   (ZLEV1),     1)
  ZWA = REAL (ILEV1B) - ZLEV1
  ZWB = ZLEV1 - REAL (ILEV1B)
  P (1:KOFF, :, ILEV2, :) = ZWA * Z (1:KOFF, :, ILEV1A, :) + ZWB * Z (1:KOFF, :, ILEV1B, :) 
ENDDO


END SUBROUTINE

SUBROUTINE INTERPOLATE5 (KFLEVG, KOFF, P)

INTEGER :: KFLEVG, KOFF
REAL, ALLOCATABLE :: P (:,:,:,:,:)
REAL :: Z (LBOUND (P, 1):UBOUND (P, 1), &
         & LBOUND (P, 2):UBOUND (P, 2), &
         & LBOUND (P, 3):UBOUND (P, 3), &
         & LBOUND (P, 4):UBOUND (P, 4), &
         & LBOUND (P, 5):UBOUND (P, 5))
INTEGER :: ILEV1A, ILEV1B, ILEV2, NLEV1, NLEV2
REAL :: ZWA, ZWB, ZLEV1, ZLEV2

Z = P

NLEV1 = SIZE (P, 3)
NLEV2 = KFLEVG

DEALLOCATE (P)

ALLOCATE (P (LBOUND (Z, 1):UBOUND (Z, 1), &
           & LBOUND (Z, 2):UBOUND (Z, 2), &
           & KFLEVG, &
           & LBOUND (Z, 4):UBOUND (Z, 4), &
           & LBOUND (Z, 5):UBOUND (Z, 5)))

DO ILEV2 = 1, NLEV2
  ZLEV2 = REAL (ILEV2 - 1) / REAL (NLEV2 -1)
  ZLEV1 = 1. + ZLEV2 * REAL (NLEV1 - 1)
  ILEV1B = MIN (CEILING (ZLEV1), NLEV1)
  ILEV1A = MAX (FLOOR   (ZLEV1),     1)

  IF (ILEV1A == ILEV1B) THEN
    ZWA = 1.
    ZWB = 0.
  ELSE
    ZWA = REAL (ILEV1B) - ZLEV1
    ZWB = ZLEV1 - REAL (ILEV1A)
  ENDIF

! WRITE (*, '(" ZLEV2 = ",E12.5," ZLEV1 = ",E12.5," ILEV2 = ",I4," ILEV1A = ",I4," ZWA = ",E12.5," ILEV1B = ",I4," ZWB = ",E12.5)') &
!   & ZLEV2, ZLEV1, ILEV2, ILEV1A, ZWA, ILEV1B, ZWB

  P (1:KOFF, :, ILEV2, :, :) = ZWA * Z (1:KOFF, :, ILEV1A, :, :) + ZWB * Z (1:KOFF, :, ILEV1B, :, :) 
ENDDO

END SUBROUTINE

END  MODULE
