MODULE MODD_STRINGS

IMPLICIT NONE

INTEGER, PARAMETER :: S_GAUS        = 1000
INTEGER, PARAMETER :: S_CB02        = 1001
INTEGER, PARAMETER :: S_CB          = 1002
INTEGER, PARAMETER :: S_NONE        = 1003
INTEGER, PARAMETER :: S_TRIANGLE    = 1004
INTEGER, PARAMETER :: S_T           = 1005
INTEGER, PARAMETER :: S_O           = 1006
INTEGER, PARAMETER :: S_N           = 1007
INTEGER, PARAMETER :: S_S           = 1008
INTEGER, PARAMETER :: S_DEPI        = 1009
 

END MODULE
