!
IMPLICIT NONE

INTEGER      :: KLON 
INTEGER      :: KIDIA  
INTEGER      :: KFDIA  
INTEGER      :: KLEV  
INTEGER      :: KRR  
INTEGER      :: KDUM

REAL, ALLOCATABLE   :: PZZF           (:,:,:)   
REAL, ALLOCATABLE   :: PRHODJ         (:,:,:)   
REAL, ALLOCATABLE   :: PEXNREF        (:,:,:)   
REAL, ALLOCATABLE   :: PRHODREF       (:,:,:)   
REAL, ALLOCATABLE   :: PPABSM         (:,:,:)   
REAL, ALLOCATABLE   :: PTHT           (:,:,:)   
REAL, ALLOCATABLE   :: PRT            (:,:,:,:) 
REAL, ALLOCATABLE   :: PSIGS          (:,:,:)   
REAL, ALLOCATABLE   :: PMFCONV        (:,:,:)   
REAL, ALLOCATABLE   :: PRC_MF         (:,:,:)   
REAL, ALLOCATABLE   :: PRI_MF         (:,:,:)   
REAL, ALLOCATABLE   :: PCF_MF         (:,:,:)   
REAL, ALLOCATABLE   :: PTHS           (:,:,:)   
REAL, ALLOCATABLE   :: PRS            (:,:,:,:) 
REAL, ALLOCATABLE   :: PRS_OUT        (:,:,:,:) 
REAL, ALLOCATABLE   :: PSRCS          (:,:,:)   
REAL, ALLOCATABLE   :: PSRCS_OUT      (:,:,:)   
REAL, ALLOCATABLE   :: PCLDFR         (:,:,:)   
REAL, ALLOCATABLE   :: PCLDFR_OUT     (:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HRC       (:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HRC_OUT   (:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HCF       (:,:,:)   
REAL, ALLOCATABLE   :: PHLC_HCF_OUT   (:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HRI       (:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HRI_OUT   (:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HCF       (:,:,:)   
REAL, ALLOCATABLE   :: PHLI_HCF_OUT   (:,:,:)   

REAL, ALLOCATABLE   :: ZRS            (:,:,:,:) 
REAL, ALLOCATABLE   :: ZZZ            (:,:,:)   
INTEGER             :: IFILE

CHARACTER(LEN=32) :: CLFILE

CALL GETARG (1, CLFILE)

KRR=6

IFILE=7
OPEN(IFILE, FILE=TRIM (CLFILE), FORM='UNFORMATTED') 

READ (IFILE) KLON, KDUM, KLEV

ALLOCATE (PZZF         (KLON,1,KLEV))
ALLOCATE (PRHODJ       (KLON,1,KLEV))
ALLOCATE (PEXNREF      (KLON,1,KLEV))
ALLOCATE (PRHODREF     (KLON,1,KLEV))
ALLOCATE (PPABSM       (KLON,1,KLEV))
ALLOCATE (PTHT         (KLON,1,KLEV))
ALLOCATE (PRT          (KLON,1,KLEV,KRR))
ALLOCATE (PSIGS        (KLON,1,KLEV))
ALLOCATE (PMFCONV      (KLON,1,KLEV))
ALLOCATE (PRC_MF       (KLON,1,KLEV))
ALLOCATE (PRI_MF       (KLON,1,KLEV))
ALLOCATE (PCF_MF       (KLON,1,KLEV))
ALLOCATE (PTHS         (KLON,1,KLEV))
ALLOCATE (PRS          (KLON,1,KLEV,KRR))
ALLOCATE (PRS_OUT      (KLON,1,KLEV,KRR))
ALLOCATE (PSRCS        (KLON,1,KLEV))
ALLOCATE (PSRCS_OUT    (KLON,1,KLEV))
ALLOCATE (PCLDFR       (KLON,1,KLEV))
ALLOCATE (PCLDFR_OUT   (KLON,1,KLEV))
ALLOCATE (ZRS          (KLON,1,KLEV,0:KRR))
ALLOCATE (ZZZ          (KLON,1,KLEV))

ALLOCATE (PHLC_HRC     (KLON,1,KLEV))
ALLOCATE (PHLC_HRC_OUT (KLON,1,KLEV))
ALLOCATE (PHLC_HCF     (KLON,1,KLEV))
ALLOCATE (PHLC_HCF_OUT (KLON,1,KLEV))
ALLOCATE (PHLI_HRI     (KLON,1,KLEV))
ALLOCATE (PHLI_HRI_OUT (KLON,1,KLEV))
ALLOCATE (PHLI_HCF     (KLON,1,KLEV))
ALLOCATE (PHLI_HCF_OUT (KLON,1,KLEV))

READ (IFILE) PRHODJ
READ (IFILE) PEXNREF
READ (IFILE) PRHODREF
READ (IFILE) PSIGS
READ (IFILE) PMFCONV
READ (IFILE) PPABSM
READ (IFILE) ZZZ
READ (IFILE) PCF_MF
READ (IFILE) PRC_MF
READ (IFILE) PRI_MF
READ (IFILE) ZRS
READ (IFILE) PRS
READ (IFILE) PTHS

READ (IFILE) PRS_OUT
READ (IFILE) PSRCS_OUT
READ (IFILE) PCLDFR_OUT
READ (IFILE) PHLC_HRC_OUT
READ (IFILE) PHLC_HCF_OUT
READ (IFILE) PHLI_HRI_OUT
READ (IFILE) PHLI_HCF_OUT

CLOSE(IFILE)

END 
