
FC2P = nvfortran -mp -byteswapio -Mlarge_arrays -fast -O3                -r8 -DUSE_OPENMP
FC0P = nvfortran -mp -byteswapio -Mlarge_arrays       -O0 -g -Ktrap=inv  -r8 -DUSE_OPENMP

CC = pgcc -mp -DLINUX

FC = $(FC2P)


